###
# DO NOT EDIT THIS FILE
# Auto generated file by R class plugin
###

<#list languageEntryList as languageEntry>
	<#list languageEntry.valueMap?keys as prop>
	
${languageEntry.encodedKey}="${languageEntry.valueMap[prop]}";
 		 
	</#list>
</#list>
